server.port: 18080

security:
  user:
    name: 'user'           # Default user name.
    password: 'password'   # Password for the default user name. A random password is logged on startup by default.
    role: 'USER'           # Granted roles for the default user name.
  basic.enabled: true

logging.level:
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure.security: INFO